# Generated by Django 4.1.3 on 2023-01-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anil_3_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Anil_3_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Anil_4_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Babu_2_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Babu_2_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Babu_3_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Babu_3_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Babu_4_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Cassian_1_2_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Cassian_1_2_b',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Devaraj_3_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='four_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=36)),
                ('FP', models.CharField(max_length=36)),
                ('SP', models.CharField(max_length=36)),
                ('BR', models.CharField(max_length=36)),
                ('TP', models.CharField(max_length=36)),
                ('FRP', models.CharField(max_length=36)),
                ('LP', models.CharField(max_length=36)),
                ('FTP', models.CharField(max_length=36)),
                ('STP', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='four_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=36)),
                ('FP', models.CharField(max_length=36)),
                ('SP', models.CharField(max_length=36)),
                ('BR', models.CharField(max_length=36)),
                ('TP', models.CharField(max_length=36)),
                ('FRP', models.CharField(max_length=36)),
                ('LP', models.CharField(max_length=36)),
                ('FTP', models.CharField(max_length=36)),
                ('STP', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Narender_1_1_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Narender_1_1_b',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Narender_4_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Naveen_1_2_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Naveen_1_2_b',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Naveen_2_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='one_1_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=36)),
                ('FP', models.CharField(max_length=36)),
                ('SP', models.CharField(max_length=36)),
                ('BR', models.CharField(max_length=36)),
                ('TP', models.CharField(max_length=36)),
                ('FRP', models.CharField(max_length=36)),
                ('LP', models.CharField(max_length=36)),
                ('FTP', models.CharField(max_length=36)),
                ('STP', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='one_1_b',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=36)),
                ('FP', models.CharField(max_length=36)),
                ('SP', models.CharField(max_length=36)),
                ('BR', models.CharField(max_length=36)),
                ('TP', models.CharField(max_length=36)),
                ('FRP', models.CharField(max_length=36)),
                ('LP', models.CharField(max_length=36)),
                ('FTP', models.CharField(max_length=36)),
                ('STP', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='one_2_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=36)),
                ('FP', models.CharField(max_length=36)),
                ('SP', models.CharField(max_length=36)),
                ('BR', models.CharField(max_length=36)),
                ('TP', models.CharField(max_length=36)),
                ('FRP', models.CharField(max_length=36)),
                ('LP', models.CharField(max_length=36)),
                ('FTP', models.CharField(max_length=36)),
                ('STP', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='one_2_b',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=36)),
                ('FP', models.CharField(max_length=36)),
                ('SP', models.CharField(max_length=36)),
                ('BR', models.CharField(max_length=36)),
                ('TP', models.CharField(max_length=36)),
                ('FRP', models.CharField(max_length=36)),
                ('LP', models.CharField(max_length=36)),
                ('FTP', models.CharField(max_length=36)),
                ('STP', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Saithirumal_1_1_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=22)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Saithirumal_1_1_b',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Saithirumal_2_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Saithirumal_2_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Santhosh_3_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Santhosh_3_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Subhan_3_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Subhan_3_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Subhan_4_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Subharao_1_1_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Subharao_1_1_b',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Subharao_2_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Subharao_3_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Subharao_3_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='three_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=36)),
                ('FP', models.CharField(max_length=36)),
                ('SP', models.CharField(max_length=36)),
                ('BR', models.CharField(max_length=36)),
                ('TP', models.CharField(max_length=36)),
                ('FRP', models.CharField(max_length=36)),
                ('LP', models.CharField(max_length=36)),
                ('FTP', models.CharField(max_length=36)),
                ('STP', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='three_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=36)),
                ('FP', models.CharField(max_length=36)),
                ('SP', models.CharField(max_length=36)),
                ('BR', models.CharField(max_length=36)),
                ('TP', models.CharField(max_length=36)),
                ('FRP', models.CharField(max_length=36)),
                ('LP', models.CharField(max_length=36)),
                ('FTP', models.CharField(max_length=36)),
                ('STP', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='two_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=36)),
                ('FP', models.CharField(max_length=36)),
                ('SP', models.CharField(max_length=36)),
                ('BR', models.CharField(max_length=36)),
                ('TP', models.CharField(max_length=36)),
                ('FRP', models.CharField(max_length=36)),
                ('LP', models.CharField(max_length=36)),
                ('FTP', models.CharField(max_length=36)),
                ('STP', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='two_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=36)),
                ('FP', models.CharField(max_length=36)),
                ('SP', models.CharField(max_length=36)),
                ('BR', models.CharField(max_length=36)),
                ('TP', models.CharField(max_length=36)),
                ('FRP', models.CharField(max_length=36)),
                ('LP', models.CharField(max_length=36)),
                ('FTP', models.CharField(max_length=36)),
                ('STP', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Venkat_1_1_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Venkat_1_1_b',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Venkat_1_2_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Venkat_1_2_b',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Zulfiquar_1_1_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Zulfiquar_1_1_b',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Zulfiquar_1_2_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Zulfiquar_1_2_b',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Zulfiquar_2_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAY', models.CharField(max_length=25)),
                ('Classtime', models.CharField(max_length=25)),
            ],
        ),
    ]
